///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest123
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddPanel recording.
    /// </summary>
    [TestModule("5f20f947-7e9c-42a6-a273-fea5a48dd43d", ModuleType.Recording, 1)]
    public partial class AddPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest123Repository repository.
        /// </summary>
        public static MyTest123Repository repo = MyTest123Repository.Instance;

        static AddPanel instance = new AddPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddPanel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddPanel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.SomeListItem1' at 49;49.", repo.FormMe.SomeListItem1Info, new RecordItemIndex(0));
            repo.FormMe.SomeListItem1.Click("49;49");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddANewPanel.ButtonOK' at 43;9.", repo.AddANewPanel.ButtonOKInfo, new RecordItemIndex(1));
            repo.AddANewPanel.ButtonOK.Click("43;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.PARTExpandButton' at 12;10.", repo.FormMe.PARTExpandButtonInfo, new RecordItemIndex(2));
            repo.FormMe.PARTExpandButton.Click("12;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMe.BuiltInLoopA0Of125' at 85;8.", repo.FormMe.BuiltInLoopA0Of125Info, new RecordItemIndex(3));
            repo.FormMe.BuiltInLoopA0Of125.Click("85;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
