///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest123
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest123Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("80ecf968-1a23-4bde-b1d3-73374d994a31")]
    public partial class MyTest123Repository : RepoGenBaseFolder
    {
        static MyTest123Repository instance = new MyTest123Repository();
        MyTest123RepositoryFolders.FormMeAppFolder _formme;
        MyTest123RepositoryFolders.CreateNewProjectAppFolder _createnewproject;
        MyTest123RepositoryFolders.AddANewPanelAppFolder _addanewpanel;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest123Repository element repository.
        /// </summary>
        [RepositoryFolder("80ecf968-1a23-4bde-b1d3-73374d994a31")]
        public static MyTest123Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest123Repository() 
            : base("MyTest123Repository", "/", null, 0, false, "80ecf968-1a23-4bde-b1d3-73374d994a31", ".\\RepositoryImages\\MyTest123Repository80ecf968.rximgres")
        {
            _formme = new MyTest123RepositoryFolders.FormMeAppFolder(this);
            _createnewproject = new MyTest123RepositoryFolders.CreateNewProjectAppFolder(this);
            _addanewpanel = new MyTest123RepositoryFolders.AddANewPanelAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("80ecf968-1a23-4bde-b1d3-73374d994a31")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormMe folder.
        /// </summary>
        [RepositoryFolder("b05011e4-1031-4866-ad13-1127af7c1691")]
        public virtual MyTest123RepositoryFolders.FormMeAppFolder FormMe
        {
            get { return _formme; }
        }

        /// <summary>
        /// The CreateNewProject folder.
        /// </summary>
        [RepositoryFolder("7f4c8323-641c-4e77-b139-0af7d268443a")]
        public virtual MyTest123RepositoryFolders.CreateNewProjectAppFolder CreateNewProject
        {
            get { return _createnewproject; }
        }

        /// <summary>
        /// The AddANewPanel folder.
        /// </summary>
        [RepositoryFolder("a27953cb-ab15-4d28-972b-2fa59a56a919")]
        public virtual MyTest123RepositoryFolders.AddANewPanelAppFolder AddANewPanel
        {
            get { return _addanewpanel; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest123RepositoryFolders
    {
        /// <summary>
        /// The FormMeAppFolder folder.
        /// </summary>
        [RepositoryFolder("b05011e4-1031-4866-ad13-1127af7c1691")]
        public partial class FormMeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _normaltextInfo;
            RepoItemInfo _textnewInfo;
            RepoItemInfo _sometextInfo;
            RepoItemInfo _somelistitemInfo;
            RepoItemInfo _somebuttonInfo;
            RepoItemInfo _somelistitem1Info;
            RepoItemInfo _partexpandbuttonInfo;
            RepoItemInfo _builtinloopa0of125Info;
            RepoItemInfo _text813pInfo;
            RepoItemInfo _cp820Info;
            RepoItemInfo _partclosebuttonInfo;

            /// <summary>
            /// Creates a new FormMe  folder.
            /// </summary>
            public FormMeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMe", "/form[@automationid='me']", parentFolder, 30000, null, true, "b05011e4-1031-4866-ad13-1127af7c1691", "")
            {
                _normaltextInfo = new RepoItemInfo(this, "NormalText", "progressbar/container[@automationid='PART_AutoHideControl']/?/?/button[@automationid='PART_ApplicationButton']/?/?/text[@automationid='normalText']", 30000, null, "d98df69e-1c46-4a7f-ab15-3c67ddf66631");
                _textnewInfo = new RepoItemInfo(this, "TextNew", ".//container[@name='PART_Content' and @caption='New']/text[@caption='New']", 30000, null, "2d151c13-5fe9-4ad2-acfe-ee32f150f325");
                _sometextInfo = new RepoItemInfo(this, "SomeText", "progressbar/container[20]/text/container[7]/text[@caption='']/text[@caption='']", 30000, null, "4bad743a-e7d9-436a-8ee5-730de583a37a");
                _somelistitemInfo = new RepoItemInfo(this, "SomeListItem", ".//text[@caption='Recently Used Markets']/button[2]/list[@automationid='PART_Groups']/listitem[@index='0']", 30000, null, "623aa09e-6303-4c5b-ac7d-7d08d526cd9b");
                _somebuttonInfo = new RepoItemInfo(this, "SomeButton", "progressbar/container[20]/text/container[6]/button", 30000, null, "c090ef64-dd5c-421a-a7e4-0a3943f83727");
                _somelistitem1Info = new RepoItemInfo(this, "SomeListItem1", "progressbar/container[@automationid='PART_AutoHideControl']/list/list[2]/list[1]/list[2]/container[@automationid='PART_ItemsPresenter']/button[@automationid='PART_Caption']/list[@automationid='PART_Groups']/listitem[@index='3']", 30000, null, "af5a7f35-9dff-4634-989b-37f7f2769ae2");
                _partexpandbuttonInfo = new RepoItemInfo(this, "PARTExpandButton", "progressbar/picture[11]/tree/container[7]/container[@caption='']/indicator[2]/button[@automationid='PART_ExpandButton']", 30000, null, "1b809a4e-9fa5-4940-870c-a0dcc2cd8a5d");
                _builtinloopa0of125Info = new RepoItemInfo(this, "BuiltInLoopA0Of125", "progressbar/picture[11]/tree/container[7]//text[@caption>'Built-in Loop-A (0 of 125']", 30000, null, "55ebde5f-12e5-439c-b8a0-24431d2382a3");
                _text813pInfo = new RepoItemInfo(this, "Text813P", "progressbar/container[@automationid='PART_AutoHideControl']/list/list[2]/list[1]/list[5]/container[@automationid='PART_ItemsPresenter']/button[@automationid='PART_Caption']/list[@automationid='PART_Groups']/?/?/text[@caption='813 P']", 30000, null, "6195f68c-ddd1-49ca-bdb7-2783c9af56dd");
                _cp820Info = new RepoItemInfo(this, "CP820", "progressbar/container[@automationid='PART_AutoHideControl']/list/list[2]/list[1]/list[6]/container[@automationid='PART_ItemsPresenter']/button[@automationid='PART_Caption']/list[@automationid='PART_Groups']/?/?/text[@caption='CP 820']", 30000, null, "5acc38e9-60d2-428a-9a49-4cd5d10d6821");
                _partclosebuttonInfo = new RepoItemInfo(this, "PARTCloseButton", "container[@automationid='Root_Grid']//button[@automationid='PART_CloseButton']", 30000, null, "6f9f75c9-7869-4c5f-bdd3-01a2c4dbd18c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b05011e4-1031-4866-ad13-1127af7c1691")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b05011e4-1031-4866-ad13-1127af7c1691")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NormalText item.
            /// </summary>
            [RepositoryItem("d98df69e-1c46-4a7f-ab15-3c67ddf66631")]
            public virtual Ranorex.Text NormalText
            {
                get
                {
                    return _normaltextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NormalText item info.
            /// </summary>
            [RepositoryItemInfo("d98df69e-1c46-4a7f-ab15-3c67ddf66631")]
            public virtual RepoItemInfo NormalTextInfo
            {
                get
                {
                    return _normaltextInfo;
                }
            }

            /// <summary>
            /// The TextNew item.
            /// </summary>
            [RepositoryItem("2d151c13-5fe9-4ad2-acfe-ee32f150f325")]
            public virtual Ranorex.Text TextNew
            {
                get
                {
                    return _textnewInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextNew item info.
            /// </summary>
            [RepositoryItemInfo("2d151c13-5fe9-4ad2-acfe-ee32f150f325")]
            public virtual RepoItemInfo TextNewInfo
            {
                get
                {
                    return _textnewInfo;
                }
            }

            /// <summary>
            /// The SomeText item.
            /// </summary>
            [RepositoryItem("4bad743a-e7d9-436a-8ee5-730de583a37a")]
            public virtual Ranorex.Text SomeText
            {
                get
                {
                    return _sometextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SomeText item info.
            /// </summary>
            [RepositoryItemInfo("4bad743a-e7d9-436a-8ee5-730de583a37a")]
            public virtual RepoItemInfo SomeTextInfo
            {
                get
                {
                    return _sometextInfo;
                }
            }

            /// <summary>
            /// The SomeListItem item.
            /// </summary>
            [RepositoryItem("623aa09e-6303-4c5b-ac7d-7d08d526cd9b")]
            public virtual Ranorex.ListItem SomeListItem
            {
                get
                {
                    return _somelistitemInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem item info.
            /// </summary>
            [RepositoryItemInfo("623aa09e-6303-4c5b-ac7d-7d08d526cd9b")]
            public virtual RepoItemInfo SomeListItemInfo
            {
                get
                {
                    return _somelistitemInfo;
                }
            }

            /// <summary>
            /// The SomeButton item.
            /// </summary>
            [RepositoryItem("c090ef64-dd5c-421a-a7e4-0a3943f83727")]
            public virtual Ranorex.Button SomeButton
            {
                get
                {
                    return _somebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SomeButton item info.
            /// </summary>
            [RepositoryItemInfo("c090ef64-dd5c-421a-a7e4-0a3943f83727")]
            public virtual RepoItemInfo SomeButtonInfo
            {
                get
                {
                    return _somebuttonInfo;
                }
            }

            /// <summary>
            /// The SomeListItem1 item.
            /// </summary>
            [RepositoryItem("af5a7f35-9dff-4634-989b-37f7f2769ae2")]
            public virtual Ranorex.ListItem SomeListItem1
            {
                get
                {
                    return _somelistitem1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SomeListItem1 item info.
            /// </summary>
            [RepositoryItemInfo("af5a7f35-9dff-4634-989b-37f7f2769ae2")]
            public virtual RepoItemInfo SomeListItem1Info
            {
                get
                {
                    return _somelistitem1Info;
                }
            }

            /// <summary>
            /// The PARTExpandButton item.
            /// </summary>
            [RepositoryItem("1b809a4e-9fa5-4940-870c-a0dcc2cd8a5d")]
            public virtual Ranorex.Button PARTExpandButton
            {
                get
                {
                    return _partexpandbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTExpandButton item info.
            /// </summary>
            [RepositoryItemInfo("1b809a4e-9fa5-4940-870c-a0dcc2cd8a5d")]
            public virtual RepoItemInfo PARTExpandButtonInfo
            {
                get
                {
                    return _partexpandbuttonInfo;
                }
            }

            /// <summary>
            /// The BuiltInLoopA0Of125 item.
            /// </summary>
            [RepositoryItem("55ebde5f-12e5-439c-b8a0-24431d2382a3")]
            public virtual Ranorex.Text BuiltInLoopA0Of125
            {
                get
                {
                    return _builtinloopa0of125Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BuiltInLoopA0Of125 item info.
            /// </summary>
            [RepositoryItemInfo("55ebde5f-12e5-439c-b8a0-24431d2382a3")]
            public virtual RepoItemInfo BuiltInLoopA0Of125Info
            {
                get
                {
                    return _builtinloopa0of125Info;
                }
            }

            /// <summary>
            /// The Text813P item.
            /// </summary>
            [RepositoryItem("6195f68c-ddd1-49ca-bdb7-2783c9af56dd")]
            public virtual Ranorex.Text Text813P
            {
                get
                {
                    return _text813pInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text813P item info.
            /// </summary>
            [RepositoryItemInfo("6195f68c-ddd1-49ca-bdb7-2783c9af56dd")]
            public virtual RepoItemInfo Text813PInfo
            {
                get
                {
                    return _text813pInfo;
                }
            }

            /// <summary>
            /// The CP820 item.
            /// </summary>
            [RepositoryItem("5acc38e9-60d2-428a-9a49-4cd5d10d6821")]
            public virtual Ranorex.Text CP820
            {
                get
                {
                    return _cp820Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CP820 item info.
            /// </summary>
            [RepositoryItemInfo("5acc38e9-60d2-428a-9a49-4cd5d10d6821")]
            public virtual RepoItemInfo CP820Info
            {
                get
                {
                    return _cp820Info;
                }
            }

            /// <summary>
            /// The PARTCloseButton item.
            /// </summary>
            [RepositoryItem("6f9f75c9-7869-4c5f-bdd3-01a2c4dbd18c")]
            public virtual Ranorex.Button PARTCloseButton
            {
                get
                {
                    return _partclosebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseButton item info.
            /// </summary>
            [RepositoryItemInfo("6f9f75c9-7869-4c5f-bdd3-01a2c4dbd18c")]
            public virtual RepoItemInfo PARTCloseButtonInfo
            {
                get
                {
                    return _partclosebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The CreateNewProjectAppFolder folder.
        /// </summary>
        [RepositoryFolder("7f4c8323-641c-4e77-b139-0af7d268443a")]
        public partial class CreateNewProjectAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new CreateNewProject  folder.
            /// </summary>
            public CreateNewProjectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateNewProject", "/form[@title='Create New Project']", parentFolder, 30000, null, true, "7f4c8323-641c-4e77-b139-0af7d268443a", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[1]//button[@text='OK']", 30000, null, "b448f894-26b6-439e-bf8b-09efc7dd4e76");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f4c8323-641c-4e77-b139-0af7d268443a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f4c8323-641c-4e77-b139-0af7d268443a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("b448f894-26b6-439e-bf8b-09efc7dd4e76")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("b448f894-26b6-439e-bf8b-09efc7dd4e76")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The AddANewPanelAppFolder folder.
        /// </summary>
        [RepositoryFolder("a27953cb-ab15-4d28-972b-2fa59a56a919")]
        public partial class AddANewPanelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new AddANewPanel  folder.
            /// </summary>
            public AddANewPanelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddANewPanel", "/form[@title='Add a New Panel']", parentFolder, 30000, null, true, "a27953cb-ab15-4d28-972b-2fa59a56a919", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[1]//button[@text='OK']", 30000, null, "e014fb9e-04d5-4b69-8954-8bfa7abc0398");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a27953cb-ab15-4d28-972b-2fa59a56a919")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a27953cb-ab15-4d28-972b-2fa59a56a919")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("e014fb9e-04d5-4b69-8954-8bfa7abc0398")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("e014fb9e-04d5-4b69-8954-8bfa7abc0398")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
